name: Tecnología en tus Manos
favicon: null
layout_spectrum: 0.969572
typography_spectrum: 0.157072
title: Tecnología en tus Manos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#88B0C0'
    - '#083038'
    - '#6080B0'
    - '#1040A0'
    - '#4868F0'
  brandStrength: 0.67023
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
