analytics: {}
color:
  brandColors:
    - '#88B0C0'
    - '#083038'
    - '#6080B0'
    - '#1040A0'
    - '#4868F0'
  brandStrength: 0.67023
  lightness: 0.628289
  rhythmicContrast: 0.708881
  saturation: 0.60444
cta: {}
layout_spectrum: 0.969572
name: Tecnología en tus Manos
opengraph: {}
purpose: {}
typography_spectrum: 0.157072
